name: 01-building-blocks
on: push
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello world !"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
          - name: Job failed
            run: |
              echo "Job succeeded"
              exit 0
          - name: Say goodbye
            run: echo "Goodbye"
